openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        "200":
          description: ""
    post:
      operationId: runSave
      summary: ""
      parameters: []
      requestBody:
        required: true
        description: Data
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/form"
      responses:
        "201":
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/form"
        "400":
          description: bad request
        "500":
          description: internal error
info:
  contact: {}
tags: []
servers: []
components:
  schemas: 
    form:
      type: object
      properties:
        _id:
          type: string
          format: uuid
          default: ""
        
      firstName: 
        type: string
      lastName: 
        type: string
      email: 
        type: string
        format: email
      countryCode: 
        type: string
      phoneNum: 
        type: string
      password: 
        type: string
      passwordConf: 
        type: string
      check1:
        type: boolean      
      check2: 
        type: boolean

      required:
        - firstName
        - lastName
        - email
        - countryCode
        - phoneNum
        - password
        - passwordConf
        - check1
        - check2

